# Generated by Django 5.0.1 on 2024-04-24 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DadosCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=30)),
                ('cpf_cnpj', models.CharField(max_length=20)),
                ('rg_ie', models.CharField(max_length=15)),
                ('data_nascimento_cliente', models.DateField()),
                ('email_cliente', models.CharField(max_length=30)),
                ('celular_cliente', models.CharField(max_length=11)),
                ('telefone_cliente', models.CharField(max_length=11)),
                ('endereco_cliente', models.CharField(max_length=60)),
                ('bairro_cliente', models.CharField(max_length=20)),
                ('cep_cliente', models.CharField(max_length=9)),
                ('cidade_cliente', models.CharField(max_length=20)),
                ('uf_cliente', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DadosCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_loja', models.CharField(max_length=30)),
                ('num_nf', models.CharField(max_length=20)),
                ('rg_ie', models.CharField(max_length=15)),
                ('data_compra', models.DateField()),
                ('cod_produto', models.CharField(max_length=30)),
                ('valor', models.CharField(max_length=11)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_chatbot.dadoscliente')),
            ],
        ),
        migrations.CreateModel(
            name='DadosComprador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_comprador', models.CharField(max_length=30)),
                ('cpf_cnpj', models.CharField(max_length=20)),
                ('rg_ie', models.CharField(max_length=15)),
                ('data_nascimento_comprador', models.DateField()),
                ('email_comprador', models.CharField(max_length=30)),
                ('celular_comprador', models.CharField(max_length=11)),
                ('telefone_comprador', models.CharField(max_length=11)),
                ('endereco_comprador', models.CharField(max_length=60)),
                ('bairro_comprador', models.CharField(max_length=20)),
                ('cep_comprador', models.CharField(max_length=9)),
                ('cidade_comprador', models.CharField(max_length=20)),
                ('uf_comprador', models.CharField(max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_chatbot.dadoscliente')),
            ],
        ),
        migrations.CreateModel(
            name='DadosEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_equipamento', models.CharField(max_length=30)),
                ('marca', models.CharField(max_length=14)),
                ('lacrado', models.CharField(max_length=15)),
                ('modelo', models.CharField(max_length=8)),
                ('num_serie', models.CharField(max_length=30)),
                ('senha_usuario', models.CharField(max_length=11)),
                ('defeito', models.CharField(max_length=300)),
                ('estado', models.CharField(max_length=300)),
                ('acessorios', models.CharField(max_length=300)),
                ('observacoes', models.CharField(max_length=300)),
                ('arquivos', models.CharField(max_length=300)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_chatbot.dadoscliente')),
            ],
        ),
    ]
