# Generated by Django 5.0.1 on 2024-04-24 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dadoscompra',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='dadoscompra',
            name='rg_ie',
        ),
        migrations.RemoveField(
            model_name='dadoscomprador',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='dadosequipamento',
            name='cliente',
        ),
    ]
