# Generated by Django 5.0.3 on 2024-05-30 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_chatbot', '0002_remove_dadoscompra_cliente_remove_dadoscompra_rg_ie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('cellphone', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='dadoscliente',
            name='uf_cliente',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='dadoscompra',
            name='num_nf',
            field=models.CharField(max_length=44),
        ),
        migrations.AlterField(
            model_name='dadoscompra',
            name='valor',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='dadoscomprador',
            name='uf_comprador',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='dadosequipamento',
            name='lacrado',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='dadosequipamento',
            name='marca',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='dadosequipamento',
            name='modelo',
            field=models.CharField(max_length=15),
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.CharField(max_length=12)),
                ('data_criacao', models.DateField()),
                ('status', models.CharField(default='Recebida', max_length=15)),
                ('dados_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_chatbot.dadoscliente')),
                ('dados_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_chatbot.dadoscompra')),
                ('dados_comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_chatbot.dadoscomprador')),
                ('dados_equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_chatbot.dadosequipamento')),
            ],
        ),
    ]
