# Generated by Django 5.0.3 on 2024-05-30 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_chatbot', '0003_customerdata_alter_dadoscliente_uf_cliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('email', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
