# Generated by Django 5.0.3 on 2024-06-07 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_chatbot', '0004_employeedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
