# Generated by Django 5.0.3 on 2024-06-07 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_chatbot', '0005_ordemservico_is_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadoscliente',
            name='celular_cliente',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='data_criacao',
            field=models.DateField(auto_now_add=True),
        ),
    ]
