# Generated by Django 5.0.1 on 2024-06-07 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_chatbot', '0006_alter_dadoscliente_celular_cliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=30)),
                ('buyer_cpf_cnpj', models.CharField(max_length=20)),
                ('buyer_rg_ie', models.CharField(max_length=15)),
                ('buyer_birthdate', models.DateField()),
                ('buyer_email', models.CharField(max_length=30)),
                ('buyer_cellphone', models.CharField(max_length=11)),
                ('buyer_telephone', models.CharField(max_length=11)),
                ('buyer_adress', models.CharField(max_length=60)),
                ('buyer_neighborhood', models.CharField(max_length=20)),
                ('buyer_zip', models.CharField(max_length=9)),
                ('buyer_city', models.CharField(max_length=20)),
                ('buyer_state', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ClientData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=30)),
                ('client_cpf_cnpj', models.CharField(max_length=20)),
                ('client_rg_ie', models.CharField(max_length=15)),
                ('client_birthdate', models.DateField()),
                ('client_email', models.CharField(max_length=30)),
                ('client_cellphone', models.CharField(max_length=11)),
                ('client_telephone', models.CharField(max_length=11)),
                ('client_adress', models.CharField(max_length=60)),
                ('client_neighborhood', models.CharField(max_length=20)),
                ('client_zip', models.CharField(max_length=9)),
                ('client_city', models.CharField(max_length=20)),
                ('client_state', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=20)),
                ('new', models.CharField(max_length=3)),
                ('model', models.CharField(max_length=15)),
                ('serial_number', models.CharField(max_length=30)),
                ('user_password', models.CharField(max_length=11)),
                ('defect', models.CharField(max_length=300)),
                ('state', models.CharField(max_length=300)),
                ('acessories', models.CharField(max_length=300)),
                ('observations', models.CharField(max_length=300)),
                ('files', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=30)),
                ('receipt_number', models.CharField(max_length=44)),
                ('purchase_date', models.DateField()),
                ('product_code', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=8)),
            ],
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='dados_cliente',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='dados_compra',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='dados_comprador',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='dados_equipamento',
        ),
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol_code', models.CharField(max_length=12)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='Recebida', max_length=15)),
                ('is_finished', models.BooleanField(default=False)),
                ('buyer_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_chatbot.buyerdata')),
                ('client_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_chatbot.clientdata')),
                ('equipment_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_chatbot.equipmentdata')),
                ('purchase_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_chatbot.purchasedata')),
            ],
        ),
        migrations.DeleteModel(
            name='DadosCliente',
        ),
        migrations.DeleteModel(
            name='DadosCompra',
        ),
        migrations.DeleteModel(
            name='DadosComprador',
        ),
        migrations.DeleteModel(
            name='DadosEquipamento',
        ),
        migrations.DeleteModel(
            name='OrdemServico',
        ),
    ]
