# Generated by Django 5.0.3 on 2024-06-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_chatbot', '0007_buyerdata_clientdata_equipmentdata_purchasedata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdata',
            name='client_cellphone',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='protocol_code',
            field=models.CharField(max_length=8),
        ),
    ]
